plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.9-SNAPSHOT'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
description = 'Demo project for Spring Boot'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
	maven { url = 'https://repo.spring.io/snapshot' }
}

dependencies {
	 /*RESTful API를 만들기 위해 필요*/
	implementation 'org.springframework.boot:spring-boot-starter-web' 
	 /*API를 보호하고 인증/인가를 처리하기 위해 필요*/
	implementation 'org.springframework.boot:spring-boot-starter-security'
	 /*데이터베이스와 상호작용을 더 쉽게 하기 위해 필요*/
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	 /*Spring Boot 3에서 Keycloak과 같은 외부 인증 서버와 연동하기 위한 표준 방식*/
	implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
	/*Keycloak 관리자 API를 호출할 수 있는 별도의 라이브러리*/
	implementation 'org.keycloak:keycloak-admin-client:22.0.5'
	implementation 'org.springframework.boot:spring-boot-starter'
	compileOnly 'org.projectlombok:lombok'
	runtimeOnly 'org.postgresql:postgresql'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}
